### ISSUE TITLE
License File

### ISSUE THREAD

**Issue by egandro** [Yashground/video-processing-app#1]
Please provice a proper License file.

Thank you.

**Comment by Yashground** [comment]
https://github.com/Yashground/video-processing-app?tab=readme-ov-file#license

I have kept it open source with MIT license, If you are looking to adopt this, I could change it to private and work together on licensing part.

Please reach me on srisaila.de@gmail.com

**Comment by egandro** [comment]
Add a license file here in the Repo. If not I can't touch the source.
